[package]
name = "surbored_server"
version = "0.1.0"
edition = "2025"

# Add to Cargo.toml
[dependencies]
axum = "0.5"
jsonwebtoken = "8.1"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
